String dbCreation = ""
"CREATE TABLE user ("
"id INTEGER  AUTO_INCREMENT,"
"username VARCHAR(50) NOT NULL,"
"password VARCHAR(15) NOT NULL,"
"PRIMARY KEY (id)"
");"
"CREATE TABLE pet ("
"id INTEGER AUTO_INCREMENT,"
"userId INTERGER,"
"icon VARCHAR(50),"
"name VARCHAR(50),"
"lastTime VARCHAR(30),"
"health REAL,"
"happy REAL,"
"hunger REAL,"
"dirt BOOLEAN,"
"sleeping BOOLEAN,"
"healthRate REAL,"
"happyRate REAL,"
"hungerRate REAL,"
"PRIMARY KEY (id),"
"FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE ON UPDATE CASCADE"
");";
